### ISSUE TITLE
Connection Definition is available at the resource level and the storage level

### ISSUE THREAD

**Issue by DImuthuUpe** [SGCI/sgci-resource-inventory#4]
There is a connection property at the top level resource properties [1] and in the storage level [2] properties. Seems like redundant. 

[1] https://github.com/SGCI/sgci-resource-inventory/blob/master/schema/resources-schema.json#L48
[2] https://github.com/SGCI/sgci-resource-inventory/blob/master/schema/resources-schema.json#L129

**Comment by scblack321** [comment]
This would be a good issue to bring up at the working session on Friday. I believe the group had settled on a design where both computeDefinition and storageDefinition have a connectionDefinition that can override the top level connectionDefinition.
 - Thanks

**Comment by joestubbs** [comment]
We refactored the spec and this is no longer applicable.
